In [1]:
import pandas as pd
from tensorflow.keras.models import load_model
import pickle
import tensorflow as tf

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1788443471.709556    9847 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1788443471.803761    9847 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1788443475.601758    9847 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [2]:
with open('label_encoder.pkl','rb') as file:
    label = pickle.load(file)

with open('onehot_encoder.pkl','rb') as file:
    onehot = pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

In [3]:
model = load_model('model.h5')

E0000 00:00:1788443478.340402    9847 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [4]:
user = {'Pclass':3,'Sex':'male','SibSp':1,'Parch':0,'Fare':76,'Embarked':'Southampton'}
user = pd.DataFrame([user])

In [5]:
user

   Pclass   Sex  SibSp  Parch  Fare     Embarked
0       3  male      1      0    76  Southampton

In [6]:
user['Sex'] = label.transform(user['Sex'])

In [7]:
embarked = onehot.transform(user[['Embarked']])

In [ ]:
embarked = pd.DataFrame(embarked,columns=onehot.get_feature_names_out())

In [9]:
embarked

   Embarked_Cherbourg  Embarked_Queenstown  Embarked_Southampton
0                 0.0                  0.0                   1.0

In [10]:
df = pd.concat([user.drop(columns=['Embarked']),embarked],axis=1)

In [11]:
df

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,3,1,1,0,76,0.0,0.0,1.0

In [12]:
df[['Pclass','SibSp','Parch','Fare']] = scaler.transform(df[['Pclass','SibSp','Parch','Fare']])

In [13]:
df

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,0.82409,1,0.442505,-0.469229,0.896815,0.0,0.0,1.0

In [14]:
y = model.predict(df)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

In [15]:
y

array([[0.99949986]], dtype=float32)