In [68]:
import pandas as pd

## Data Gathering

In [69]:
# Data Gathering
df = pd.read_csv('huge_1M_titanic.csv')

## Data Preprocessing

In [70]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1310,1,1,"Name1310, Miss. Surname1310",female,NaN,0,0,SOTON/O2 3101272,76.760165,NaN,C
1,1311,0,3,"Name1311, Col. Surname1311",male,29.0,0,0,223596,10.193097,NaN,S
2,1312,0,3,"Name1312, Mr. Surname1312",male,20.0,0,0,54636,12.029416,C83,C
3,1313,0,3,"Name1313, Mr. Surname1313",male,27.0,0,0,PC 17760,13.429448,NaN,S
4,1314,0,3,"Name1314, Mr. Surname1314",male,32.0,0,0,364512,4.840769,E33,C

In [71]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
999995,1001305,0,2,"Name1001305, Mr. Surname1001305",male,27.0,0,0,244358,26.196512,NaN,S
999996,1001306,1,1,"Name1001306, Miss. Surname1001306",female,33.0,0,0,349221,102.555248,NaN,S
999997,1001307,0,3,"Name1001307, Mr. Surname1001307",male,NaN,1,0,PC 17601,8.274807,NaN,S
999998,1001308,0,2,"Name1001308, Mr. Surname1001308",male,35.0,1,0,112050,0.000000,B102,S
999999,1001309,1,1,"Name1001309, Miss. Surname1001309",female,37.0,1,0,28403,57.720316,NaN,S

In [72]:
df.shape

(1000000, 12)

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PassengerId  1000000 non-null  int64
 1   Survived     1000000 non-null  int64
 2   Pclass       1000000 non-null  int64
 3   Name         1000000 non-null  object
 4   Sex          1000000 non-null  object
 5   Age          801400 non-null   float64
 6   SibSp        1000000 non-null  int64
 7   Parch        1000000 non-null  int64
 8   Ticket       1000000 non-null  object
 9   Fare         1000000 non-null  float64
 10  Cabin        229805 non-null   object
 11  Embarked     997760 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 91.6+ MB

In [74]:
df.drop(columns=['PassengerId','Name','Age','Ticket','Cabin'],inplace=True)

In [75]:
df.isnull().sum()

Survived       0
Pclass         0
Sex            0
SibSp          0
Parch          0
Fare           0
Embarked    2240
dtype: int64

In [76]:
df['Embarked'].mode()[0]

'S'

In [77]:
df['Embarked'].value_counts()

Embarked
S    729468
C    186846
Q     81446
Name: count, dtype: int64

## Data Cleaning

In [78]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [79]:
df['Embarked'].replace({'C':'Cherbourg','S':'Southampton','Q':'Queenstown'},inplace=True)

/tmp/ipykernel_18814/2836720248.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].replace({'C':'Cherbourg','S':'Southampton','Q':'Queenstown'},inplace=True)

In [80]:
df['Fare'] = df['Fare'].astype(int)

In [81]:
df

        Survived  Pclass     Sex  SibSp  Parch  Fare     Embarked
0              1       1  female      0      0    76    Cherbourg
1              0       3    male      0      0    10  Southampton
2              0       3    male      0      0    12    Cherbourg
3              0       3    male      0      0    13  Southampton
4              0       3    male      0      0     4    Cherbourg
...          ...     ...     ...    ...    ...   ...          ...
999995         0       2    male      0      0    26  Southampton
999996         1       1  female      0      0   102  Southampton
999997         0       3    male      1      0     8  Southampton
999998         0       2    male      1      0     0  Southampton
999999         1       1  female      1      0    57  Southampton

[1000000 rows x 7 columns]

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   Survived  1000000 non-null  int64
 1   Pclass    1000000 non-null  int64
 2   Sex       1000000 non-null  object
 3   SibSp     1000000 non-null  int64
 4   Parch     1000000 non-null  int64
 5   Fare      1000000 non-null  int64
 6   Embarked  1000000 non-null  object
dtypes: int64(5), object(2)
memory usage: 53.4+ MB

# Data Encoding & Scaling
- Label Encoder
  - Binary
- Ordinal Encoder
  - Ordinal Data
- Nominal Encoder
  - Normal data

In [83]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [84]:
labelencoder = LabelEncoder()
onehotencoder = OneHotEncoder(sparse_output=False)

In [85]:
df['Sex'] = labelencoder.fit_transform(df['Sex'])

In [86]:
embarked = onehotencoder.fit_transform(df[['Embarked']])

In [87]:
embarked

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], shape=(1000000, 3))

In [88]:
embarked = pd.DataFrame(embarked,columns=onehotencoder.get_feature_names_out())

In [89]:
df = pd.concat([df,embarked],axis=1)

In [90]:
df.drop(columns=['Embarked'],inplace=True)

In [91]:
df

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,1,1,0,0,0,76,1.0,0.0,0.0
1,0,3,1,0,0,10,0.0,0.0,1.0
2,0,3,1,0,0,12,1.0,0.0,0.0
3,0,3,1,0,0,13,0.0,0.0,1.0
4,0,3,1,0,0,4,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
999995,0,2,1,0,0,26,0.0,0.0,1.0
999996,1,1,0,0,0,102,0.0,0.0,1.0
999997,0,3,1,1,0,8,0.0,0.0,1.0
999998,0,2,1,1,0,0,0.0,0.0,1.0
999999,1,1,0,1,0,57,0.0,0.0,1.0

In [92]:
from sklearn.preprocessing import StandardScaler

In [93]:
ss = StandardScaler()

In [94]:
num_cols = ['Pclass','SibSp','Parch','Fare']

In [95]:
df[num_cols] = ss.fit_transform(df[num_cols])

In [96]:
df

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,1,-1.568913,0,-0.462600,-0.469229,0.896815,1.0,0.0,0.0
1,0,0.824090,1,-0.462600,-0.469229,-0.479459,0.0,0.0,1.0
2,0,0.824090,1,-0.462600,-0.469229,-0.437754,1.0,0.0,0.0
3,0,0.824090,1,-0.462600,-0.469229,-0.416901,0.0,0.0,1.0
4,0,0.824090,1,-0.462600,-0.469229,-0.604575,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
999995,0,-0.372411,1,-0.462600,-0.469229,-0.145817,0.0,0.0,1.0
999996,1,-1.568913,0,-0.462600,-0.469229,1.438983,0.0,0.0,1.0
999997,0,0.824090,1,0.442505,-0.469229,-0.521165,0.0,0.0,1.0
999998,0,-0.372411,1,0.442505,-0.469229,-0.687986,0.0,0.0,1.0
999999,1,-1.568913,0,0.442505,-0.469229,0.500614,0.0,0.0,1.0

In [97]:
import pickle

with open('label_encoder.pkl','wb') as file:
    pickle.dump(labelencoder,file)

with open('onehot_encoder.pkl','wb') as file:
    pickle.dump(onehotencoder,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(ss,file)

## Train-Validation-Test Split

In [98]:
X = df.drop(columns=['Survived'])
Y = df['Survived']

In [99]:
X

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,-1.568913,0,-0.462600,-0.469229,0.896815,1.0,0.0,0.0
1,0.824090,1,-0.462600,-0.469229,-0.479459,0.0,0.0,1.0
2,0.824090,1,-0.462600,-0.469229,-0.437754,1.0,0.0,0.0
3,0.824090,1,-0.462600,-0.469229,-0.416901,0.0,0.0,1.0
4,0.824090,1,-0.462600,-0.469229,-0.604575,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
999995,-0.372411,1,-0.462600,-0.469229,-0.145817,0.0,0.0,1.0
999996,-1.568913,0,-0.462600,-0.469229,1.438983,0.0,0.0,1.0
999997,0.824090,1,0.442505,-0.469229,-0.521165,0.0,0.0,1.0
999998,-0.372411,1,0.442505,-0.469229,-0.687986,0.0,0.0,1.0
999999,-1.568913,0,0.442505,-0.469229,0.500614,0.0,0.0,1.0

In [100]:
Y

0         1
1         0
2         0
3         0
4         0
         ..
999995    0
999996    1
999997    0
999998    0
999999    1
Name: Survived, Length: 1000000, dtype: int64

In [104]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [106]:
x_train,x_valid,y_train,y_valid =train_test_split(x_train,y_train,test_size=0.2,random_state=42)

In [107]:
x_train

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
338664,-0.372411,1,-0.462600,-0.469229,-0.291786,0.0,0.0,1.0
171390,0.824090,0,-0.462600,-0.469229,-0.687986,0.0,0.0,1.0
66113,0.824090,0,-0.462600,-0.469229,-0.333491,0.0,0.0,1.0
981567,-1.568913,0,0.442505,-0.469229,0.813404,1.0,0.0,0.0
677093,-0.372411,1,-0.462600,-0.469229,-0.604575,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...
18622,0.824090,1,-0.462600,-0.469229,-0.437754,0.0,0.0,1.0
17191,0.824090,1,-0.462600,-0.469229,-0.562870,0.0,1.0,0.0
227647,-0.372411,0,-0.462600,0.834050,-0.291786,0.0,0.0,1.0
639540,0.824090,1,-0.462600,-0.469229,-0.687986,0.0,0.0,1.0
237899,0.824090,1,-0.462600,-0.469229,-0.437754,0.0,0.0,1.0

In [108]:
import tensorflow

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1788357020.846621   18814 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1788357022.188626   18814 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1788357027.848707   18814 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

# Model Building

In [111]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [116]:
input_shape = x_train.shape[1]

In [117]:
model = Sequential(
    [
        Dense(64,input_shape=(input_shape,),activation='relu'),
        Dense(32,activation='relu'),
        Dense(1,activation='sigmoid')
    ]
)

/home/simsol/Documents/GenAI/venv/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [127]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,069 (31.52 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,380 (21.02 KB)

In [122]:
opt = tensorflow.keras.optimizers.Adam(learning_rate= 0.01)

In [123]:
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
stopping_callback = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

In [125]:
model.fit(x_train,y_train,validation_data=(x_valid,y_valid),epochs=10,callbacks=stopping_callback)

Epoch 1/10

W0000 00:00:1788358749.845627   18814 cpu_allocator_impl.cc:82] Allocation of 20480000 exceeds 10% of free system memory.

20000/20000 ━━━━━━━━━━━━━━━━━━━━ 96s 5ms/step - accuracy: 0.8545 - loss: 0.3339 - val_accuracy: 0.8642 - val_loss: 0.3149
Epoch 2/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 70s 4ms/step - accuracy: 0.8619 - loss: 0.3179 - val_accuracy: 0.8662 - val_loss: 0.3091
Epoch 3/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 70s 4ms/step - accuracy: 0.8626 - loss: 0.3151 - val_accuracy: 0.8655 - val_loss: 0.3121
Epoch 4/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 71s 4ms/step - accuracy: 0.8633 - loss: 0.3142 - val_accuracy: 0.8647 - val_loss: 0.3130
Epoch 5/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 68s 3ms/step - accuracy: 0.8636 - loss: 0.3136 - val_accuracy: 0.8632 - val_loss: 0.3148
Epoch 6/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 69s 3ms/step - accuracy: 0.8640 - loss: 0.3128 - val_accuracy: 0.8643 - val_loss: 0.3171
Epoch 7/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 63s 3ms/step - accuracy: 0.8642 - loss: 0.3126 - val_accuracy: 0.8642 - val_loss: 0.3122

In [129]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.